"""init

Revision ID: 7a4df18e6d42
Revises: 
Create Date: 2022-06-27 04:18:51.261104

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a4df18e6d42"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "in_",
            sa.Enum(
                "Moscow",
                "SaintPetersburg",
                "Novosibirsk",
                "Yekaterinburg",
                "Kazan",
                "NizhnyNovgorod",
                "Chelyabinsk",
                "Omsk",
                "Krasnoyarsk",
                "Irkutsk",
                "Vladivostok",
                name="availablecitiesenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "out",
            sa.Enum(
                "Moscow",
                "SaintPetersburg",
                "Novosibirsk",
                "Yekaterinburg",
                "Kazan",
                "NizhnyNovgorod",
                "Chelyabinsk",
                "Omsk",
                "Krasnoyarsk",
                "Irkutsk",
                "Vladivostok",
                name="availablecitiesenum",
            ),
            nullable=True,
        ),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("min_price", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("delivery_date", sa.Integer(), nullable=True),
        sa.Column("less", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivers")
    op.execute("DROP TYPE availablecitiesenum")
    # ### end Alembic commands ###
