"""add multiplier

Revision ID: eb76b9d3dd4a
Revises: 7a4df18e6d42
Create Date: 2022-06-27 05:45:17.902607

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb76b9d3dd4a"
down_revision = "7a4df18e6d42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivers", sa.Column("weight_multiplier", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "delivers", sa.Column("volume_multiplier", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("delivers", "volume_multiplier")
    op.drop_column("delivers", "weight_multiplier")
    # ### end Alembic commands ###
